version: '3'

services:
  dev-stack:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    command: /sbin/init
    privileged: true
    ports:
      - "80:80"
      - "8000:8000"
